version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:8000"
      - "3000:3000"
      - "5173:5173"
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    networks:
      - laravel-network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=movies_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
    depends_on:
      - db
    entrypoint: ["/var/www/entrypoint.sh"]

  db:
    image: postgres:latest
    container_name: laravel-db
    environment:
      - POSTGRES_DB=movies_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  postgres_data:
